### ISSUE TITLE
OnResultTrackCallBack 手势追踪

### ISSUE THREAD

**Issue by xinnian88** [baidu/ar-sdk#14]
OnResultTrackCallBack 手势追踪 如何体验，有什么要求？demo 里面没收到事件回调

**Comment by xiegaoxi** [comment]
[main_d69a00b773f2a4cac5715edd2b5c8b0a.zip](https://github.com/baidu/ar-sdk/files/2370773/main_d69a00b773f2a4cac5715edd2b5c8b0a.zip)
1, 将上面的内容case解压
2,放到sdcard/track目录。 例如/sdcard/track/ar...
3, 运行测试列表倒数第二项(/sdcard/track/)，即可加载此case

**Comment by xinnian88** [comment]
[error.txt](https://github.com/baidu/ar-sdk/files/2385540/error.txt)
错误日志文件， 使用你给的这个模型之后，出现jni 错误。

**Comment by xinnian88** [comment]
Cause: null pointer dereference  是不是你用的代码，和master 的不一样？

**Comment by xiegaoxi** [comment]
方便的话加我微信：pxlxmx 详细沟通一下。谢谢
